### ISSUE TITLE
Problem Updating Variable 

### ISSUE THREAD

**Issue by Amitkor12** [klonyyy/STMViewer#29]
Hello, I want to express my gratitude for creating such a fantastic application that proves to be highly useful for robotics. I have downloaded the application and carefully followed the instructions, but I encountered an issue where the variables do not get updated, and the addresses are not displayed as expected.
I would appreciate any suggestions, hints, or insights you could provide regarding the issue I'm facing with.

Thank You.

**Comment by klonyyy** [comment]
Hello, could you please provide more details? For example a project file and the *.elf file you're trying to parse. I'll try to reproduce  the problem locally. Please make sure the GDB version is correct as well (#27)

**Comment by Amitkor12** [comment]
[firmware.zip](https://github.com/klonyyy/STMViewer/files/14120430/firmware.zip)
This is the elf file i am using.
The gdb version is also update to latest version 14.2

**Comment by klonyyy** [comment]
I seems to work fine on my end:
![image](https://github.com/klonyyy/STMViewer/assets/10755893/4d0fbd67-7f76-442a-acd1-e8b6327bb587)

Are there any particular variables you have troubles importing? 
Please make sure your path does not contain any spaces (#27)

**Comment by Amitkor12** [comment]
Thanks for the help.
First i tried this on windows 11. Here i did not get any response in updating variables , but with the same file on linux i was able to update the variables.
![Screenshot from 2024-02-01 12-35-53](https://github.com/klonyyy/STMViewer/assets/65597271/fb62d13e-f092-4844-81b8-2ee86337cfd6)
this is on linux ubuntu 20.04 lts.

**Comment by klonyyy** [comment]
This is strange, as my screenshot is from Windows 10. If you've got some spare time you can check for the spaces in your *.elf path. I'm curious if it's a bug.

**Comment by Amitkor12** [comment]
I checked the path of the *.elf file, and indeed, there was a space between the names. Now, after the correction, it works fine. Thanks for your support.
