### ISSUE TITLE
Debian binary package contains dev dependencies

### ISSUE THREAD

**Issue by amurzeau** [klonyyy/STMViewer#3]
Hi,

Thanks for your tool :)
The Debian package in the release page depends on dev dependencies even though it is a binary package.
I think this is the packages that need to be put as dependencies (according to `readelf -d /usr/local/STMViewer/STMViewer | grep NEEDED`):
```
libglfw3 | libglfw3-wayland
libgl1
libglib2.0-0
libgtk-3-0
libstdc++6
libusb-1.0-0
```

I also suggest to add a line `Categories=Development;` in STMViewer.desktop so STMViewer is put in the Development menu (next to STM32CubeIDE for example):
![image](https://github.com/klonyyy/STMViewer/assets/5435069/d7655c84-6ee6-4a35-b425-430c3162957c)

**Comment by klonyyy** [comment]
Hey,

Thanks for the contribution! Feel free to open new issues/PRs if you find any other improvements like this :)
