### ISSUE TITLE
Adding a variable on the running plot has a time lag

### ISSUE THREAD

**Issue by klonyyy** [klonyyy/STMViewer#32]

**Comment by koniho** [comment]
Do you mean that after adding variables to a running plot, the plot starts to have a lag to display the data points? I think I noticed the same thing. I noted that the plot scale changed quickly but the related data points didn't show up for quite some time (seconds)

**Comment by klonyyy** [comment]
Yes, exactly that. This is a known issue, though it's not critical at this time.
