### ISSUE TITLE
Importing variable

### ISSUE THREAD

**Issue by Candas1** [klonyyy/STMViewer#37]
Thanks again for this tool, I use it a lot.
The new feature for importing variables works well so far, I only have a little comment.
After importing a variable:
![image](https://github.com/klonyyy/STMViewer/assets/20670049/426f95c9-ec7a-4912-8f17-7d67d2cd0fa3)
An update is required to get the variable's address:
![image](https://github.com/klonyyy/STMViewer/assets/20670049/8967455a-9815-4179-bb32-e180c289a854)

It's not a big deal but I thought I would mention it.

**Comment by klonyyy** [comment]
Thanks for the feedback, this is something I also found a bit annoying. Adding to a TODO list.
