### ISSUE TITLE
High DPI font size

### ISSUE THREAD

**Issue by dzid26** [klonyyy/STMViewer#48]
On Windows, on 4K (set to 150% dpi) or laptop "3K" (set to 200%dpi) monitors the font looks tiny. 
![image](https://github.com/klonyyy/STMViewer/assets/841061/4adb2923-b9a3-4d29-a0c8-fe5448859429)

Changing the font size in settings doesn't work great and it's not sharp:
![image](https://github.com/klonyyy/STMViewer/assets/841061/387ba7de-ab2b-40a6-a5ac-d5e49b215eea)

**Comment by dzid26** [comment]
Workaround - override high DPI settings to "System"
![image](https://github.com/klonyyy/STMViewer/assets/841061/7817bc30-f265-4db9-b3db-ab6fd86476c2)

This works pretty good. 
On 200% DPI everything is perfectly sharp, albeit pixels are 2x big. 
![image](https://github.com/klonyyy/STMViewer/assets/841061/c8fca93a-81a6-4378-ac9a-e110e8139d75)
On 150% DPI, there is a little bit of blur, but not too bad. 
![image](https://github.com/klonyyy/STMViewer/assets/841061/8dd6e6bf-91d1-4bc4-b53f-70e34bc34447)

**Comment by klonyyy** [comment]
Was this tested on main branch? Is there still a problem or the solution that you've posted is enough?

**Comment by dzid26** [comment]
It behaved similar on main and jlink_hss branches. 

The workaround is not optimal because of lower resolution and/or blur. 
Also, the Windows bug that allows accidental dragging of an app underneath is also a bit annoying.

**Comment by dzid26** [comment]
The original report was about the v4 and v5. This was fixed probably with #42  . 
Sorry for the confusion - I didn't even notice it just worked correctly with the latest head.
