### ISSUE TITLE
CPU/GPU usage when idle

### ISSUE THREAD

**Issue by dzid26** [klonyyy/STMViewer#49]
Windows 11. 
There is constant small CPU/GPU usage even when acquisition is **stopped** and app is **minimized**. 

Can we pause the rendering at least under those conditions?

**Comment by klonyyy** [comment]
Could you show me the circumstances under which these usages take place? This is my usage when STMViewer is minimized:
![image](https://github.com/klonyyy/STMViewer/assets/10755893/83b7b1ae-b53a-4bc3-abd2-f32a4f7ae36e)

**Comment by dzid26** [comment]
In general the usage is not big (usually 2%) but it jumps to 5% periodically. 
Examples. 
(When recording is not active, the effect on GPU is slightly larger. )

https://github.com/klonyyy/STMViewer/assets/841061/79d86b5d-a6b1-4129-a473-e70b54eea0b6

https://github.com/klonyyy/STMViewer/assets/841061/58e69c3a-afc5-450b-8a8f-20b8264e1a1d




I am expecting there could be 0% when stopped. 
But if imgui is not efficient about mouse events, etc.., then at least maybe we can pause it when minimized. 

Thanks

**Comment by klonyyy** [comment]
Please let me know if the latest commit solved the issue. Thanks for bringing it out!

**Comment by dzid26** [comment]
Strangely, today, I couldn't reproduce 5% CPU spikes on any version. 

Version 0.4 & 0.5:
- When stopped CPU was mostly 0% and GPU mostly  4%.
- When minimized CPU was mostly at 0% and GPU at 0.5% average

With `GLFW_FOCUSED`:
- CPU and GPU are both 0% when not in focus.  Great.

But the cursors don't refresh when hovering.  :( 

Since the issue doesn't seem as bad as I thought, perhaps we can check for "minimized" only?  

This works:
```
if (glfwGetWindowAttrib(window, GLFW_ICONIFIED))
```

**Comment by klonyyy** [comment]
Yeah, I was thinking of the GLFW_ICONIFIED however this does not seem to limit the rendering whenever the windows is overlayed by another window (not minimized explicitly). Let's stick with it and see if someone complaints about the high CPU/GPU usage after this fix.

**Comment by dzid26** [comment]
Actually, we also could add this in the while loop:
```
		if (glfwGetWindowAttrib(window, GLFW_FOCUSED) || (tracePlotHandler->getViewerState() == PlotHandlerBase::state::RUN) || (plotHandler->getViewerState() == PlotHandlerBase::state::RUN))
			glfwSwapInterval(1);
		else
			glfwSwapInterval(4);
```

1% instead of 4% GPU usage with visible window.

**Comment by klonyyy** [comment]
Would you be willing to implement and test that in a PR to the devel branch?
