### ISSUE TITLE
STMViewer does not update variables

### ISSUE THREAD

**Issue by aareyes96** [klonyyy/STMViewer#5]
I'm using Windows.opens a console window that closes immediately and does not update the variable types.

![image](https://github.com/klonyyy/STMViewer/assets/32934707/31092b4b-c560-43ca-b9f8-467425035fb7)

![image](https://github.com/klonyyy/STMViewer/assets/32934707/137a1eb1-b010-4d43-ae93-73d8768a96b3)

**Comment by klonyyy** [comment]
Hello, 
I'm guessing you don't have GDB installed. You can get it with MinGW. Please let me know if it solved the problem. Also please remember to add it to your path if it is not added automatically on install.

**Comment by aareyes96** [comment]
Hello @klonyyy . Thanks for your reply. I have GDB installed with mingw64.
![image](https://github.com/klonyyy/STMViewer/assets/32934707/8be47443-f4fc-49b6-9664-0d1006342866)
![image](https://github.com/klonyyy/STMViewer/assets/32934707/d6b7b283-b2f1-4ee0-8c03-3ef77530aa85)

I just uncompress this file. and copy to C:/. 
![image](https://github.com/klonyyy/STMViewer/assets/32934707/9c85b65f-5fe2-4eed-b956-95617457aeea)
Also I added to PATH enviroment variable

Thanks in advance

**Comment by klonyyy** [comment]
Hello,
Could you attach the log file after a unsuccessful update attempt? It should be located under:
C:\Users\<username>\AppData\Roaming\STMViewer\logs

Could you also attach your *.elf file?

**Comment by aareyes96** [comment]
Hello @klonyyy . The file is empty.
![image](https://github.com/klonyyy/STMViewer/assets/32934707/95268bf9-940e-4896-a4de-924da35d58d1)

**Comment by aareyes96** [comment]
[test_again.zip](https://github.com/klonyyy/STMViewer/files/12028606/test_again.zip)

**Comment by Tharazi97** [comment]
Hi, I am facing the same issue. I also tried with release 0.1.1 with the same result.

**Comment by klonyyy** [comment]
> Hello @klonyyy . The file is empty. ![image](https://user-images.githubusercontent.com/32934707/252990964-95268bf9-940e-4896-a4de-924da35d58d1.png)

Did you try it after trying to update the variables? 

Can you run the gdb using the console? Could you make sure it works by typing "gdb" in the console?

**Comment by klonyyy** [comment]
It seems there is a problem with GDB versions before 12.1. I'm using 12.1 but later 13.2 should work as well. Could you try installing the newer version?

**Comment by aareyes96** [comment]
![image](https://github.com/klonyyy/STMViewer/assets/32934707/6c91b0c5-d846-449d-9073-fe2ecc13b20b)
![image](https://github.com/klonyyy/STMViewer/assets/32934707/cda98ad8-627c-4b88-a037-c5a90d080f7d)

@klonyyy Great !!!! Now is working !!!. I am very excited to use your software.. I'm using STLink-V2 clone. 

I attach the link for download the MingW with GDB 13.2 

https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.5-11.0.0-ucrt-r5/winlibs-x86_64-posix-seh-gcc-13.1.0-llvm-16.0.5-mingw-w64ucrt-11.0.0-r5.zip

Very Thanks !!!

**Comment by klonyyy** [comment]
Glad it worked, thanks! I will add a proper note in the readme in the next update.
