### ISSUE TITLE
Automatically refresh variables upon openning import from elf dialog

### ISSUE THREAD

**Issue by dzid26** [klonyyy/STMViewer#50]
Currently empty window opens up
<img width="253" alt="image" src="https://github.com/klonyyy/STMViewer/assets/841061/3b1db544-c0c8-4daa-bc65-b8863ca31bd2">
https://github.com/klonyyy/STMViewer/issues/39

**Comment by klonyyy** [comment]
Seems reasonable, adding to my TODO list.
