### ISSUE TITLE
Automatically update variable addresses after importing from ELF

### ISSUE THREAD

**Issue by dzid26** [klonyyy/STMViewer#51]
Currently new variables show NOT FOUND and needs to be updated manually with a button. Can be confusing.
<img width="492" alt="image" src="https://github.com/klonyyy/STMViewer/assets/841061/7cc80fe8-9d77-4389-b0f7-7530af595377">

**Comment by Candas1** [comment]
https://github.com/klonyyy/STMViewer/issues/37

**Comment by dzid26** [comment]
Ah, ok, it didn't make it to releases yet. 
Thanks

**Comment by klonyyy** [comment]
This is already fixed, it's not yet merged to main. If you'd like you can use the jlink_hss branch to get the latest fixed and features.
