### ISSUE TITLE
Building - STM32 Target not found

### ISSUE THREAD

**Issue by dzid26** [klonyyy/STMViewer#58]
Everything works fine when I use release. 

However when I build myself (main of jlink_hss branch) I get this:
![image](https://github.com/klonyyy/STMViewer/assets/841061/3e6ae6ae-eb92-4635-9aa3-acf0df6f9cea)

unknown chip id! 0x410  ??  Not sure if that's even related.

Any ideas?

**Comment by klonyyy** [comment]
Yes, you can see in the README.md, that you have to manually copy the ./chips directory to make it recognise your target.

**Comment by dzid26** [comment]
Ah ok, I missed it.  Maybe I thought it was a Linux instruction. 

It worked.
