### ISSUE TITLE
Can't flash board when acquisition is running

### ISSUE THREAD

**Issue by dzid26** [klonyyy/STMViewer#60]
It's an obvious limitation. 

One solution is to use https://www.st.com/en/development-tools/st-link-server.html.  But I never seen it work. It requires both apps to support it. It is not a common setup people have. 

But there might be a simple workaround which should work for everyone: 
1. when elf is deleted or change is detected, stop the acquisition and allow the board to be flashed by another program
2. refresh the variable addresses automatically
3. restart acquisition after e.g 5s. 

Each step shall be controlled in Options. 
The feature should be off by default.

Each step is useful IMO, and can be implemented one after another.

**Comment by klonyyy** [comment]
This is something I also thought about - I've already implement the detection of *.elf file change. Now I'm going to add the remaining options that you suggested.
