### ISSUE TITLE
Allow relative elf file path in cfg file

### ISSUE THREAD

**Issue by dzid26** [klonyyy/STMViewer#65]
I wanted to add project file to revision control, but it contains absolute path.

Related:
https://github.com/klonyyy/STMViewer/blob/4d22bcdeb6d0a01148aff162177f075b49920258/test/STMViewer_test/STMViewer_project/STMViewer_test.cfg#L2

**Comment by dzid26** [comment]
But does it work? 

I tried:
```
[elf]
file_path = .\.pio\build\ServoCAN_release\firmware.elf
```

or:
```
[elf]
file_path = .pio\build\ServoCAN_release\firmware.elf
```

and it fails when _updating variable addresses_. 
![image](https://github.com/klonyyy/STMViewer/assets/841061/5d74afe2-5dc7-4c1c-ac82-520897454648)

**Comment by klonyyy** [comment]
Relative means to the place the binary is run from. So you have to make sure the directory you're referring to is in the binary folder, otherwise you have to step out of it using ../ (you can see the example in my commit - I've checked it on both Windows and Ubuntu and it works fine)

**Comment by dzid26** [comment]
So this only works for your example. 

The path should be relative to cfg file location.  Can you reopen the issue?

**Comment by klonyyy** [comment]
Now I understand what you meant. Please provide a full issue description next time so that we're both on the same page.
