### ISSUE TITLE
[Feature Request] Is there any CLI capability? 

### ISSUE THREAD

**Issue by MostHated** [klonyyy/STMViewer#76]
### Version/Branch:

0.5.0

### Operating system:

Ubuntu 23.10

### Debug probe:

ST-Link

### Details:

Hey there, I was wondering if there currently is, or any plans for any CLI capability? I tried to see if ./STMViewer --help would show anything, but all it did was start the application with the GUI all messed up (seen below).

The reason I ask, is that it would be quite helpful for quicker iteration if I could do something like:

```sh
./STMViewer --cfg /path/to/my/config.cfg --start 
```
Then have that open an instance of the app and already apply the specified config file, and start the capture straight away.

I use [just](https://just.systems/man/en/) to be able to run multiple steps in my build process quicky, and it would be quite helpful to have something like the above command in there at the end, as it would be one less manual step.

 Ideally, to help with iteration, it would be also quite nice if I already have an instance of STMViewer opened and the same command gets ran again, it would then reuse the same window instance and just start the capture again, so I don't have to try and remember to go back to the window and run it again when trying things out quickly.

<details>
<summary>Trying --help</summary>

![](https://img.instance.id/b2YlyFzQCnLM/direct)

</details>

**Comment by klonyyy** [comment]
Hello, currently there is no such option. If you'd like to implement it please feel free to do so. I could recommend [CLI11](https://github.com/CLIUtils/CLI11) for this purpose so that it is easily extendable in the future. I don't think I'll have time to do this myself anytime soon. I'm puting that task on the project TODO list.
